name: KitPvP
author: mal0ne_23
description: KitPvP for AvengeTech
version: 2.0.0
api: 3.1.0
main: kitpvp\KitPvP
depend: Core

permissions:
 kitpvp.perm:
  description: Kitpvp perm blahblah
  default: true